version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: zyra-postgres

    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zyra

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: